// Session Actions
export const INITIALISE_SESSION = 'INITIALISE_SESSION'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const SESSION_ERROR = 'SESSION_ERROR'
export const SET_SESSION_STATE = 'SET_SESSION_STATE'

// Bookmarks States
export const GET_BOOKMARKS_ERROR = 'GET_BOOKMARKS_ERROR'
export const GET_BOOKMARKS_REQUEST = 'GET_BOOKMARKS_REQUEST'
export const GET_BOOKMARKS_SUCCESS = 'GET_BOOKMARKS_SUCCESS'
export const CREATE_BOOKMARK_ERROR = 'CREATE_BOOKMARK_ERROR'
export const CREATE_BOOKMARK_REQUEST = 'CREATE_BOOKMARK_REQUEST'
export const CREATE_BOOKMARK_SUCCESS = 'CREATE_BOOKMARK_SUCCESS'