// Session States
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_IN_PROGRESS = 'FORGOT_PASSWORD_IN_PROGRESS'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const INVALID = 'INVALID'
export const LOGIN_IN_PROGRESS = 'LOGIN_IN_PROGRESS'
export const LOGGED_IN = 'LOGGED_IN'
export const REGISTRATION_IN_PROGRESS = 'REGISTRATION_IN_PROGRESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTERED = 'REGISTERED'
export const UNKNOWN = 'UNKNOWN'

// Bookmarks States
export const CREATE_BOOKMARK_ERROR = 'CREATE_BOOKMARK_ERROR'
export const CREATE_BOOKMARK_IN_PROGRESS = 'CREATE_BOOKMARK_IN_PROGRESS'
export const CREATE_BOOKMARK_SUCCESS = 'CREATE_BOOKMARK_SUCCESS'
export const GETTING_BOOKMARKS_ERROR = 'GETTING_BOOKMARKS_ERROR'
export const GETTING_BOOKMARKS_IN_PROGRESS = 'GETTING_BOOKMARKS_IN_PROGRESS'
export const GETTING_BOOKMARKS_SUCCESS = 'GETTING_BOOKMARKS_SUCCESS'
